language: python
sudo: false
python:
- "2.7"
- "3.3"
install:
- pip install codecov coverage catkin_pkg catkin_tools futures python-dateutil requests rosdep yaml
script:
- nosetests --verbose --with-coverage --cover-erase --cover-package=rosrepo test
after_success:
- codecov

